# Generated by Django 6.0.1 on 2026-01-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shippingzone_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingZone',
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Liste de souhaits', 'verbose_name_plural': 'Listes de souhaits'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_price',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix barré (FCFA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description complète'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix actuel (FCFA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Courte description'),
        ),
    ]
