# Generated by Django 6.0.1 on 2026-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Quartier / Zone')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Frais de livraison')),
                ('delivery_time', models.CharField(default='24h - 48h', max_length=100, verbose_name='Délai estimé')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
            },
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Togo', max_length=100, verbose_name='Pays'),
        ),
    ]
