# Generated by Django 6.0.1 on 2026-01-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingzone_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paygate_tx_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction PayGate'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Méthode (Moov/TMoney)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Paiement confirmé'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/', verbose_name='Reçu PDF'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payé (À préparer)'), ('processing', 'En cours de traitement'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
