# Generated by Django 6.0.1 on 2026-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paygate_tx_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de port'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_updated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Stock mis à jour'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paygate_tx_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='delivery_time',
            field=models.CharField(default='24h', max_length=100, verbose_name='Délai estimé'),
        ),
    ]
