# Generated by Django 6.0.1 on 2026-02-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien de paiement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paygate_tx_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction Bkapay'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Frais de port'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix unitaire'),
        ),
    ]
