# Generated by Django 6.0.1 on 2026-01-17 11:42

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('image', models.ImageField(upload_to=apps.core.models.upload_to_site_path, verbose_name='Image')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='URL de redirection')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LE GUIDE COMPLET DE LA MÉDITATION', max_length=200, verbose_name='Nom du site')),
                ('headline', models.CharField(blank=True, max_length=255, verbose_name='Texte principal affiché')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone_primary', models.CharField(blank=True, max_length=30, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.core.models.upload_to_site_path, verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.core.models.upload_to_site_path, verbose_name='Favicon')),
                ('theme_primary', models.CharField(default='#1e0b3b', help_text='Ex: #1e0b3b', max_length=7, verbose_name='Couleur principale (hex)')),
                ('theme_accent', models.CharField(default='#d4af37', help_text='Ex: #d4af37', max_length=7, verbose_name='Couleur accent (hex)')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texte de pied de page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Réseau / Nom')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_class', models.CharField(blank=True, help_text='Ex: fab fa-facebook-f ou icône CSS utilisée par le front', max_length=200, verbose_name='Classe icône (optionnel)')),
            ],
            options={
                'verbose_name': 'Lien social',
                'verbose_name_plural': 'Liens sociaux',
            },
        ),
    ]
